export const PLANT_LIBRARY = [
  // Herbs
  { 
    id: 'basil', 
    name: 'Basil', 
    emoji: '🌿', 
    size: 1, 
    category: 'herbs',
    description: 'Aromatic herb perfect for cooking',
    spacing: 12, // inches apart
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 60,
    companionPlants: ['tomato', 'pepper', 'oregano'],
    avoidPlants: ['rue', 'thyme'],
    soilType: ['loamy', 'sandy'],
    difficulty: 'Easy'
  },
  { 
    id: 'oregano', 
    name: 'Oregano', 
    emoji: '🌿', 
    size: 1, 
    category: 'herbs',
    description: 'Mediterranean herb with strong flavor',
    spacing: 10,
    sunlight: 'Full Sun',
    waterNeeds: 'Low',
    daysToMaturity: 80,
    companionPlants: ['basil', 'tomato', 'pepper'],
    avoidPlants: [],
    soilType: ['loamy', 'sandy', 'clay'],
    difficulty: 'Easy'
  },
  { 
    id: 'rosemary', 
    name: 'Rosemary', 
    emoji: '🌿', 
    size: 2, 
    category: 'herbs',
    description: 'Woody perennial herb',
    spacing: 24,
    sunlight: 'Full Sun',
    waterNeeds: 'Low',
    daysToMaturity: 90,
    companionPlants: ['sage', 'thyme', 'lavender'],
    avoidPlants: ['mint', 'basil'],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Medium'
  },
  { 
    id: 'parsley', 
    name: 'Parsley', 
    emoji: '🌿', 
    size: 1, 
    category: 'herbs',
    description: 'Versatile culinary herb',
    spacing: 6,
    sunlight: 'Partial Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 70,
    companionPlants: ['tomato', 'carrot', 'chives'],
    avoidPlants: ['lettuce'],
    soilType: ['loamy', 'clay'],
    difficulty: 'Easy'
  },
  { 
    id: 'mint', 
    name: 'Mint', 
    emoji: '🌿', 
    size: 1, 
    category: 'herbs',
    description: 'Refreshing herb that spreads quickly',
    spacing: 18,
    sunlight: 'Partial Sun',
    waterNeeds: 'High',
    daysToMaturity: 90,
    companionPlants: ['cabbage', 'broccoli'],
    avoidPlants: ['parsley', 'chamomile'],
    soilType: ['loamy', 'clay'],
    difficulty: 'Easy'
  },
  { 
    id: 'cilantro', 
    name: 'Cilantro', 
    emoji: '🌿', 
    size: 1, 
    category: 'herbs',
    description: 'Fresh herb popular in Mexican cuisine',
    spacing: 6,
    sunlight: 'Partial Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 50,
    companionPlants: ['tomato', 'spinach', 'chives'],
    avoidPlants: ['fennel'],
    soilType: ['loamy', 'sandy'],
    difficulty: 'Easy'
  },
  { 
    id: 'thyme', 
    name: 'Thyme', 
    emoji: '🌿', 
    size: 1, 
    category: 'herbs',
    description: 'Small leaves with intense flavor',
    spacing: 9,
    sunlight: 'Full Sun',
    waterNeeds: 'Low',
    daysToMaturity: 75,
    companionPlants: ['rosemary', 'sage', 'oregano'],
    avoidPlants: [],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Easy'
  },

  // Vegetables
  { 
    id: 'tomato', 
    name: 'Tomato', 
    emoji: '🍅', 
    size: 2, 
    category: 'vegetables',
    description: 'Popular garden vegetable',
    spacing: 24,
    sunlight: 'Full Sun',
    waterNeeds: 'High',
    daysToMaturity: 75,
    companionPlants: ['basil', 'oregano', 'parsley', 'carrot'],
    avoidPlants: ['fennel', 'corn', 'broccoli'],
    soilType: ['loamy', 'sandy'],
    difficulty: 'Medium'
  },
  { 
    id: 'carrot', 
    name: 'Carrot', 
    emoji: '🥕', 
    size: 1, 
    category: 'vegetables',
    description: 'Root vegetable rich in beta-carotene',
    spacing: 3,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 70,
    companionPlants: ['tomato', 'chives', 'leek', 'radish'],
    avoidPlants: ['dill', 'parsnip'],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Easy'
  },
  { 
    id: 'lettuce', 
    name: 'Lettuce', 
    emoji: '🥬', 
    size: 1, 
    category: 'vegetables',
    description: 'Cool-season leafy green',
    spacing: 8,
    sunlight: 'Partial Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 45,
    companionPlants: ['carrot', 'radish', 'onion'],
    avoidPlants: ['broccoli', 'parsley'],
    soilType: ['loamy', 'clay'],
    difficulty: 'Easy'
  },
  { 
    id: 'cabbage', 
    name: 'Cabbage', 
    emoji: '🥬', 
    size: 2, 
    category: 'vegetables',
    description: 'Cool-season brassica vegetable',
    spacing: 18,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 90,
    companionPlants: ['onion', 'potato', 'celery'],
    avoidPlants: ['tomato', 'strawberry'],
    soilType: ['loamy', 'clay'],
    difficulty: 'Medium'
  },
  { 
    id: 'pepper', 
    name: 'Bell Pepper', 
    emoji: '🫑', 
    size: 2, 
    category: 'vegetables',
    description: 'Sweet and colorful peppers',
    spacing: 18,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 70,
    companionPlants: ['basil', 'oregano', 'onion'],
    avoidPlants: ['fennel', 'kohlrabi'],
    soilType: ['loamy', 'sandy'],
    difficulty: 'Medium'
  },
  { 
    id: 'radish', 
    name: 'Radish', 
    emoji: '🔴', 
    size: 1, 
    category: 'vegetables',
    description: 'Fast-growing root vegetable',
    spacing: 2,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 30,
    companionPlants: ['carrot', 'lettuce', 'spinach'],
    avoidPlants: ['hyssop'],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Easy'
  },
  { 
    id: 'spinach', 
    name: 'Spinach', 
    emoji: '🥬', 
    size: 1, 
    category: 'vegetables',
    description: 'Nutrient-rich leafy green',
    spacing: 6,
    sunlight: 'Partial Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 40,
    companionPlants: ['radish', 'peas', 'strawberry'],
    avoidPlants: ['potato', 'sunflower'],
    soilType: ['loamy', 'clay'],
    difficulty: 'Easy'
  },
  { 
    id: 'broccoli', 
    name: 'Broccoli', 
    emoji: '🥦', 
    size: 2, 
    category: 'vegetables',
    description: 'Nutritious brassica vegetable',
    spacing: 18,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 85,
    companionPlants: ['onion', 'celery', 'potato'],
    avoidPlants: ['tomato', 'lettuce'],
    soilType: ['loamy', 'clay'],
    difficulty: 'Medium'
  },
  { 
    id: 'cucumber', 
    name: 'Cucumber', 
    emoji: '🥒', 
    size: 3, 
    category: 'vegetables',
    description: 'Vining vegetable, needs support',
    spacing: 36,
    sunlight: 'Full Sun',
    waterNeeds: 'High',
    daysToMaturity: 55,
    companionPlants: ['radish', 'beans', 'corn'],
    avoidPlants: ['aromatic herbs', 'potato'],
    soilType: ['loamy', 'sandy'],
    difficulty: 'Medium'
  },
  { 
    id: 'zucchini', 
    name: 'Zucchini', 
    emoji: '🥒', 
    size: 3, 
    category: 'vegetables',
    description: 'Prolific summer squash',
    spacing: 36,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 50,
    companionPlants: ['nasturtium', 'radish', 'beans'],
    avoidPlants: ['potato'],
    soilType: ['loamy', 'sandy'],
    difficulty: 'Easy'
  },

  // Fruits
  { 
    id: 'strawberry', 
    name: 'Strawberry', 
    emoji: '🍓', 
    size: 1, 
    category: 'fruits',
    description: 'Sweet perennial berry',
    spacing: 14,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 90,
    companionPlants: ['spinach', 'lettuce', 'chives'],
    avoidPlants: ['cabbage', 'broccoli'],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Medium'
  },
  { 
    id: 'blueberry', 
    name: 'Blueberry', 
    emoji: '🫐', 
    size: 3, 
    category: 'fruits',
    description: 'Acidic soil loving berry bush',
    spacing: 48,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 365, // Takes a year to establish
    companionPlants: ['azalea', 'rhododendron'],
    avoidPlants: ['tomato', 'pepper'],
    soilType: ['acidic', 'sandy'],
    difficulty: 'Hard'
  },
  { 
    id: 'raspberry', 
    name: 'Raspberry', 
    emoji: '🍇', 
    size: 2, 
    category: 'fruits',
    description: 'Cane berry that spreads',
    spacing: 24,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 365,
    companionPlants: ['garlic', 'chives', 'turnip'],
    avoidPlants: ['potato', 'tomato'],
    soilType: ['loamy', 'sandy'],
    difficulty: 'Medium'
  },
  { 
    id: 'blackberry', 
    name: 'Blackberry', 
    emoji: '🖤', 
    size: 3, 
    category: 'fruits',
    description: 'Thorny cane berry with large fruit',
    spacing: 36,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 365,
    companionPlants: ['grapes', 'tansy', 'hyssop'],
    avoidPlants: ['raspberry', 'potato'],
    soilType: ['loamy', 'clay'],
    difficulty: 'Medium'
  },
  { 
    id: 'apple', 
    name: 'Apple Tree', 
    emoji: '🍎', 
    size: 4, 
    category: 'fruits',
    description: 'Classic fruit tree for temperate climates',
    spacing: 120, // 10 feet
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 1095, // 3 years to fruit
    companionPlants: ['chives', 'nasturtium', 'comfrey'],
    avoidPlants: ['walnut', 'potato'],
    soilType: ['loamy', 'sandy'],
    difficulty: 'Hard'
  },
  { 
    id: 'pear', 
    name: 'Pear Tree', 
    emoji: '🍐', 
    size: 4, 
    category: 'fruits',
    description: 'Sweet fruit tree with delicate flowers',
    spacing: 120,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 1095,
    companionPlants: ['apple', 'cherry', 'plum'],
    avoidPlants: ['walnut'],
    soilType: ['loamy', 'clay'],
    difficulty: 'Hard'
  },
  { 
    id: 'cherry', 
    name: 'Cherry Tree', 
    emoji: '🍒', 
    size: 4, 
    category: 'fruits',
    description: 'Beautiful spring blooms and sweet fruit',
    spacing: 120,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 1460, // 4 years
    companionPlants: ['apple', 'pear', 'plum'],
    avoidPlants: ['oak', 'pine'],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Hard'
  },
  { 
    id: 'peach', 
    name: 'Peach Tree', 
    emoji: '🍑', 
    size: 4, 
    category: 'fruits',
    description: 'Fuzzy sweet stone fruit',
    spacing: 120,
    sunlight: 'Full Sun',
    waterNeeds: 'High',
    daysToMaturity: 1095,
    companionPlants: ['basil', 'tansy', 'comfrey'],
    avoidPlants: ['tomato', 'potato'],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Hard'
  },
  { 
    id: 'orange', 
    name: 'Orange Tree', 
    emoji: '🍊', 
    size: 4, 
    category: 'fruits',
    description: 'Citrus tree for warm climates',
    spacing: 144, // 12 feet
    sunlight: 'Full Sun',
    waterNeeds: 'High',
    daysToMaturity: 1095,
    companionPlants: ['lemon', 'lime', 'grapefruit'],
    avoidPlants: ['walnut'],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Hard'
  },
  { 
    id: 'lemon', 
    name: 'Lemon Tree', 
    emoji: '🍋', 
    size: 3, 
    category: 'fruits',
    description: 'Tart citrus perfect for cooking',
    spacing: 120,
    sunlight: 'Full Sun',
    waterNeeds: 'High',
    daysToMaturity: 1095,
    companionPlants: ['orange', 'lime', 'rosemary'],
    avoidPlants: [],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Hard'
  },
  { 
    id: 'lime', 
    name: 'Lime Tree', 
    emoji: '🟢', 
    size: 3, 
    category: 'fruits',
    description: 'Small citrus with intense flavor',
    spacing: 120,
    sunlight: 'Full Sun',
    waterNeeds: 'High',
    daysToMaturity: 1095,
    companionPlants: ['lemon', 'orange', 'cilantro'],
    avoidPlants: [],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Hard'
  },
  { 
    id: 'grape', 
    name: 'Grape Vine', 
    emoji: '🍇', 
    size: 3, 
    category: 'fruits',
    description: 'Climbing vine producing clusters of fruit',
    spacing: 72, // 6 feet
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 730, // 2 years
    companionPlants: ['blackberry', 'hyssop', 'oregano'],
    avoidPlants: ['cabbage', 'radish'],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Medium'
  },
  { 
    id: 'watermelon', 
    name: 'Watermelon', 
    emoji: '🍉', 
    size: 4, 
    category: 'fruits',
    description: 'Large sprawling vine with huge fruit',
    spacing: 72,
    sunlight: 'Full Sun',
    waterNeeds: 'High',
    daysToMaturity: 90,
    companionPlants: ['nasturtium', 'oregano', 'marigold'],
    avoidPlants: ['potato', 'tomato'],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Medium'
  },
  { 
    id: 'cantaloupe', 
    name: 'Cantaloupe', 
    emoji: '🍈', 
    size: 3, 
    category: 'fruits',
    description: 'Sweet orange melon',
    spacing: 48,
    sunlight: 'Full Sun',
    waterNeeds: 'High',
    daysToMaturity: 85,
    companionPlants: ['corn', 'radish', 'nasturtium'],
    avoidPlants: ['potato', 'cucumber'],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Medium'
  },
  { 
    id: 'fig', 
    name: 'Fig Tree', 
    emoji: '🟤', 
    size: 4, 
    category: 'fruits',
    description: 'Mediterranean fruit tree',
    spacing: 120,
    sunlight: 'Full Sun',
    waterNeeds: 'Low',
    daysToMaturity: 730,
    companionPlants: ['comfrey', 'nasturtium'],
    avoidPlants: [],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Medium'
  },
  { 
    id: 'avocado', 
    name: 'Avocado Tree', 
    emoji: '🥑', 
    size: 4, 
    category: 'fruits',
    description: 'Creamy fruit tree for warm climates',
    spacing: 180, // 15 feet
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 1460, // 4 years
    companionPlants: ['citrus', 'comfrey'],
    avoidPlants: [],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Hard'
  },

  // Flowers
  { 
    id: 'marigold', 
    name: 'Marigold', 
    emoji: '🌼', 
    size: 1, 
    category: 'flowers',
    description: 'Pest-repelling companion flower',
    spacing: 8,
    sunlight: 'Full Sun',
    waterNeeds: 'Low',
    daysToMaturity: 50,
    companionPlants: ['tomato', 'pepper', 'eggplant'],
    avoidPlants: [],
    soilType: ['sandy', 'loamy'],
    difficulty: 'Easy'
  },
  { 
    id: 'nasturtium', 
    name: 'Nasturtium', 
    emoji: '🌸', 
    size: 1, 
    category: 'flowers',
    description: 'Edible flower that repels pests',
    spacing: 12,
    sunlight: 'Full Sun',
    waterNeeds: 'Low',
    daysToMaturity: 55,
    companionPlants: ['cucumber', 'zucchini', 'radish'],
    avoidPlants: [],
    soilType: ['sandy', 'poor'],
    difficulty: 'Easy'
  },
  { 
    id: 'sunflower', 
    name: 'Sunflower', 
    emoji: '🌻', 
    size: 4, 
    category: 'flowers',
    description: 'Tall flower that attracts pollinators',
    spacing: 24,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 85,
    companionPlants: ['corn', 'beans'],
    avoidPlants: ['potato', 'pole beans'],
    soilType: ['loamy', 'clay'],
    difficulty: 'Easy'
  },
  { 
    id: 'lavender', 
    name: 'Lavender', 
    emoji: '💜', 
    size: 2, 
    category: 'flowers',
    description: 'Fragrant purple flowers, drought tolerant',
    spacing: 24,
    sunlight: 'Full Sun',
    waterNeeds: 'Low',
    daysToMaturity: 90,
    companionPlants: ['rosemary', 'thyme', 'sage'],
    avoidPlants: [],
    soilType: ['sandy', 'rocky'],
    difficulty: 'Easy'
  },
  { 
    id: 'rose', 
    name: 'Rose Bush', 
    emoji: '🌹', 
    size: 2, 
    category: 'flowers',
    description: 'Classic flowering shrub',
    spacing: 36,
    sunlight: 'Full Sun',
    waterNeeds: 'Moderate',
    daysToMaturity: 120,
    companionPlants: ['lavender', 'marigold', 'chives'],
    avoidPlants: ['large trees'],
    soilType: ['loamy', 'clay'],
    difficulty: 'Medium'
  }
];